---
title: "Project Milestones"
format:
  html: 
    number-sections: false
---

The student project report is the central assessment item of the module for [Examination and Grading](index.qmd#examination).

Projects shall be done in **teams**.

This list of milestones guides through the preparation, presentation and delivery of your report during the semester.


## Milestone 0: Project teams and project topic fixed {#m0}

- Teams shall be 🙍‍♀️🙎 to 🙎🙍‍♀️🙎‍♂️🙍‍♀️🙎. Teams with more members should have more story points and at the final presentation each member should present at least one story point. 
- [Form: Project and Team Check-in](https://forms.office.com/e/UZb7NFxLZB) for project ideas filled. 
- Project discussed in individual meeting with instructor.


## Milestone 1: **Project pitch** {#m1}

**For each project:** <5 min presentation answering: 

- 🗃️ What is the data?
- 💬 At least one story points/insights (max. 3 story points)
- 📊 At least one visual created with the data (max. 2 visuals)

Mode of presentation will be specified later. 

**Target Achievements:** 

-   Data and topic chosen
-   Teams formed
-   Project repository cloned, rendering of report and presentation tested
-   Project pitch done


## Milestone 2: **Main insight** 💡 {#m2}

**Target Achievements:** 

-   Target audience described
-   List of main insights in your report drafted (about 3-6 or more when the team is large)
-   Prioritized what will be the main insights

## Milestone 3: **Visual Drafts** 📊📈📉️{#m3}

**Target Achievements:** 

-   For each insight
    -   a visual drafted in the report or the presentation (a draft can be a first coded visual, or even photo of a sketch on paper)
    -   notes and ideas for the final version

## Milestone 4: **Data story and storyboard** 📖  {#m4}

**Target Achievements:** 

-   Have all your story points (e.g. as post its) drafted as a story board on paper (or in a digital tool).
-   Draft slide titles in the presentaton slidedeck. 

## Milestone 5: **Presentation** 💬  {#m5}

**Target Achievements:** 

-   Finalized your slidedeck as part of the project delivery. (Improvements are allowed afterwards.)
-   [Told your data story with the help of your slidedeck in class!]{style="color:red;"}

## Milestone 6: **Final report** 📄  {#m6}

**Target Achievements:** 

-   Finalized your written report.
-   Checked if the rendering works and the html-files opened and a appear as they should in a local browser.
-   Cleaned repository (removed unnecessary files etc.) and [pushed a final commit by]{style="color:red;"} the deadline is set in the [Academic Calendar]({{< var link.academic_calendar >}}).
-   Decided if you want to publish your report on the web.

## Delivery

For details about the project report the [Examination and Grading in the Syllabus](index.qmd#examination)

Essential parts of your delivery:

-   Report
-   Slidedeck

Optional:

-   Dashboard if not included in website.
-   Reproduction code if not folded in the report or report appendix.
