---
week: "02"
title: "Week 02"
format:
  html: 
    number-sections: false
---

## Material

Slides [Direct Link](../lectures/W02.qmd)

```{=html}
<iframe src="https://{{< var org.name >}}.github.io/Website/lectures/W{{< meta week >}}.html" frameborder="0" width="800" height="550" style="border:1px solid black;" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
```

Find the live recording in the [Course's Team's Recording Folder]({{< var teams.recording_folder_link >}}). 

### Assigments / Readings

1. **Read Chapter 2 in {{< var dykes2019 >}}**, consult the [Reading  Remarks](../readings.qmd) for the Chapter. 
    - Enter your reading comments in the Form [My Comments: Chapter 2](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=PpeO9wtcuEq715iHyVqOvWY2_0g0xmdMnWy3R6Eqe89UOUNMOTJKWDcwWTNFNURPQVhMSkIzRTBCSC4u)
2. **Explore different bubble plot** using different variables on `x`, `y`, `size`, and `color` and filter for an interesting year. Decide for an interesting one and post it in the Teams Channel "Bubble Plots".
    1. Explore some option in the interface of the last slides in this week's slides
    2. Make your own repository from the [template repository VisCom_Playground](https://github.com/CU-F26-MDSSB-MET-03-VisCommDataStory/VisCom_Playground). Use the green button "Use this template". After creation, clone it to your computer, and start working in the script `CountryBubbles.R`. 
    3. Work own visual. Improve it such that it is on the level you would like to see it when it would be posted on social media. For example:
        - Interesting selection of variables and year(s)
        - Good title
        - Descriptive axis labels
        - Nice legend(s) if needed
        - Selected data point annotations
        - Caption with more information and your name
    4. Make the aspect ratio nice. Copy the figure and post it in the **Teams Channel "Bubble Plots"**
3. **Search the internet for a data visual you find interesting and well-crafted.** It can be anything which shows some insight through data visualization. Copy it and post it in the **Teams Channel "Interesting Data Visuals"**
4. (Optional) Familiarize yourself with HTML (revealjs) presentations with quarto: Render `Presentation_Datasaurus.qmd` in the Playground repo with quarto and understand how slides and so on are made.  

## Checklist

Check the boxes when done, and feel the "done" 🙂.

- [ ] Reading Comments for Chapter 2 submitted. 
- [ ] Bubble Plot posted in the Teams Channel "Bubble Plots"
- [ ] Interesting data visual found on the internet and submitted in the Team Channel "Interesting Data Visuals"
